language: python
python:
  - "2.7"
  - "3.7"
  - "pypy"
  - "pypy3"
stages:
  - test

jobs:
  include:
    - stage: test
      name: Unit Tests
      script: pytest
    - install: install
      name: Install Requiriments.txt
      script: pip install -r requirements.txt